services:
  - postgresql
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - 'node'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
cache:
  yarn: true
  directories:
    - node_modules
install: yarn install --ignore-optional --pure-lockfile
env:
  - DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
after_success:
  - npm run lint
  - npm run coveralls
